---

- name: Getting list of partitions
  shell: df -hl --output=target | grep -v 'Mounted on'
  register: part

- name: Getting privileged commands
  shell: find {{ item }} -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null
  register: priv_commands
  with_items: "{{ part.stdout_lines }}"

- name: Adding privileged commands rules
  lineinfile:
    path: "{{ auditd_manage_configuration_directory }}/50-stig.rules"
    state: present
    line: -a always,exit -F path={{ item.1 }} -F perm=x -F auid>=1000 -F auid!=4294967295 -F key=special-config-changes
  loop: "{{ priv_commands.results|subelements('stdout_lines') }}"
  when: ansible_distribution == "RedHat"
  notify:
    - restart auditd
    - restart auditd - rhel7